# Sample .travis.yml for R projects.
# See README.md for instructions.

language: r
sudo: required
warnings_are_errors: true

env:
  - global:
    - R_BUILD_ARGS='--no-manual'
    - R_CHECK_ARGS='--no-manual --as-cran'

r_github_packages:
  - Rexamine/stringi

install:
  - Rscript -e "library(stringi); stri_install_icudt()"

notifications:
  email:
    on_success: change
    on_failure: change
