# Sample .travis.yml for R projects.
# See README.md for instructions.

language: r
sudo: required
warnings_are_errors: true

env:
  - global:
    - R_BUILD_ARGS='--no-manual'
    - R_CHECK_ARGS='--no-manual --as-cran'

r_github_packages:
  - Rexamine/stringi

notifications:
  email:
    on_success: change
    on_failure: change

# One can also restrict the branches to test, see
#   http://about.travis-ci.org/docs/user/build-configuration/#Specify-branches-to-build
branches:
  except:
    - /-expt$/
